server:
  port: 8080
  contextPath: /TransAps
---
spring:
  profiles: local,default
datasource:
  transaps:
    url: jdbc:h2:~/test
    username: user
    password: password
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
    azure:
      cosmosdb:
        sql:
          host: https://transaps.documents.azure.com:443/
          key: nVXgoAVn6oURiLTZpOUawsbFzijq3TtFY3YEYWRoaifZzysPHJ1sUKO4OQZ11bTZeZqKnYTbI4f08EHIdyMsoA==
          appDB: APP_DB
          appCollection: APP_COLLECTION
      storage:
        account: transaps
        key: XMTFJWiL7icOBkWpD0JlkqrSJDRCF866weQGqiN1wjQRlg/s3BAQzYdWEcd4wMWxy6vTy7PUS4MuCMC5/ng4IA==
        appIconContainer: app-icon-container
---
spring:
  profiles: prod
datasource:
  transaps:
    url: jdbc:mysql://localhost:3306/transaps
    username: user
    password: password
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect