server:
  port: 8080
  contextPath: /TransAps
---
spring:
  profiles: local,default
datasource:
  transaps:
    url: jdbc:h2:~/test
    username: user
    password: password
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  transaps:
    url: jdbc:mysql://localhost:3306/transaps
    username: user
    password: password
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect